@url = http://localhost:8081/api

@json = 11

################## about user
###
get {{url}}/getFans?id=100001

###
get {{url}}/recommend?userid=100005

###
get {{url}}/getFriends?id=100001

###
get {{url}}/getFollowSinger?id=100001

###
get {{url}}/getUser?id=100001

################### about songlist
###
get {{url}}/getSongList?id=100001

###
get {{url}}/getSongListById?id=3000555
###
get {{url}}/showCreatedSongList?id=100001

###
get {{url}}/getFavorite?id=100001

###
get {{url}}/getSongListSavedNum?songlistid=3000508

###
get {{url}}/getSongsOfSongList?songlistid=3000001

###
get {{url}}/getNumOfSongList?songlistid=3000508


###
get {{url}}/createNewSonglist?name=新歌单&userid=100050

###
get {{url}}/KeepSongList?userid=100011&songlistid=3000544

###
get {{url}}/cancelKeepSongList?userid=100011&songlistid=3000544


###
get {{url}}/isSonglistSaved?userid=100001&songlistid=3000536



#################### about singer
###
get {{url}}/getSingerBySong?songid=4000000

###
get {{url}}/getSinger?singerid=

###
get{{url}}/getSongInfo?songid=4000005

###
get {{url}}/getAlbum?albumid=1000000

###
get {{url}}/isFollowedSinger?uid=100001&sid=200000

###
get {{url}}/changeFollowSinger?uid=100001&sid=200000

###
get {{url}}/getSongAndAlbumOfSinger?singerid=200000&userid=

#################### about friend
###
get {{url}}/showFollowUser?id=100000

###
get {{url}}/isFollowed?uid=100000&fid=100001

###
get {{url}}/changeFollow?uid=100000&fid=100001

#################### about buy
###
get {{url}}/setVIP?id=100000

###
get {{url}}/buyMusic?id=100000&mid=4000001&type=s

###
get {{url}}/charge?id=100000&money=50

###
get {{url}}/showBoughtSongs?id=100000

###
get {{url}}/showBoughtAlbums?id=100000

#################### about search

###
get {{url}}/Search/Song?words=a

###
get {{url}}/Search/SongList?words=啊

###
get {{url}}/Search/Album?words=

###
get {{url}}/Search/User?words=l

###
get {{url}}/searchSinger?word=王


#################### about song

###
get {{url}}/favoriteSong?userid=100001&songid=4000000

###
get {{url}}/KeepSong?songlistid=100002&songid=94238

###
get {{url}}/unKeepSong?songlistid=100002&songid=94238

###
get {{url}}/getSong?songid=94238

###
get {{url}}//buildSong

###
get {{url}}/isSongBought?songid=4000000&albumid=1000000&userid=100001
