
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:MusicDB
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.example.demo.entity